swagger: '2.0'
info:
  title: University Recommendation API
  version: '0.0'
  license:
    name: GNU Affero General Public License Version 3
    url: http://www.gnu.org/licenses/agpl-3.0.en.html
externalDocs:
  description: GitHub Repository
  url: https://github.com/osu-mist/web-api-skeleton
host: localhost
schemes:
  - http
basePath: /api/v0
consumes:
  - text/plain
produces:
  - application/json
paths:
  /:
    get:
      summary: Get information
      description: Build and runtime information about the application.
      responses:
        200:
          description: Object containing information
          schema:
            $ref: '#/definitions/Info'
  /sample:
    get:
      summary: Get message
      description: This is a sample resource that returns a short message.
      responses:
        200:
          description: A short message
          schema:
            type: string
        404:
          description: Not found
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Post message
      description: This is a sample resource that returns the message it receives.
      parameters:
        - name: message
          in: body
          schema:
            type: string
          required: true
      responses:
        200:
          description: The message received
          schema:
            type: string
        404:
          description: Not found
          schema:
            $ref: '#/definitions/Error'

definitions:
  Archive:
    type: object
    properties:
      id:
        type: integer
        format: int32
        description: Unique identifier for the archive
      year:
        type: integer
        format: int32
      stu_src:
        type: string
        description: Province that the students come from
      stu_type:
        type: string
        description: Type of the student-[arts, sciences]
      batch:
        type: integer
        format: int32
        description: An integer indicates the batch-[1, 2, 3]

  University:
    type: object
    properties:
      id:
        type: integer
        format: int32
        description: Unique 4-digit identifier for the university
      name:
        type: string
        description: Name of the university
      province:
        type: string
        description: Province where the university locates
      is_985:
        type: boolean
        description: is the university in the 985 program
      is_211:
        type: boolean
        description: is the university in the 211 program

  Ranking:
    type: object
    properties:
      id:
        type: integer
        format: int32
        description: Unique identifier for the ranking
      a_id:
        type: integer
        format: int32
        description: Identifier that related to the archive
      score:
        type: integer
        format: int32
        description: Score of the examination
      stu_count:
        type: integer
        format: int32
        description: Number of students received the score
      ranking:
        type: integer
        format: int32
        description: Ranking of the score in the province

  BatchScore:
    type: object
    properties:
      id:
        type: integer
        format: int32
        description: Unique identifier for the batchScore
      a_id:
        type: integer
        format: int32
        description: Identifier that related to the archive
      min_score:
        type: integer
        format: int32
        description: Minimum score of the batch

  EnrollmentUniversity:
    type: object
    properties:
      id:
        type: integer
        format: int32
        description: Unique identifier for the EnrollmentUniversity
      u_id:
        type: integer
        format: int32
        description: Identifier that related to the university
      a_id:
        type: integer
        format: int32
        description: Identifier that related to the archive
      score_avg:
        type: integer
        format: int32
        description: Average score for the university
      stu_count:
        type: integer
        format: int32
        description: Number of students enrolled in the university

  EnrollmentMajor:
    type: object
    properties:
      id:
        type: integer
        format: int32
        description: Unique identifier for the EnrollmentMajor
      u_id:
        type: integer
        format: int32
        description: Identifier that related to the university
      a_id:
        type: integer
        format: int32
        description: Identifier that related to the archive
      major:
        type: string
      score_avg:
        type: integer
        format: int32
        description: Average score for the major

  Translation:
    type: object
    properties:
      id:
        type: integer
        format: int32
        description: Unique identifier for the Translation
      english:
        type: string
      chinese:
        type: string

  Error:
    type: object
    properties:
      status:
        type: integer
        format: int32
      developerMessage:
        type: string
      userMesage:
        type: string
      code:
        type: integer
      details:
        type: string
