swagger: '2.0'
info:
  title: University Recommendation API
  version: '0.0'
  license:
    name: GNU Affero General Public License Version 3
    url: http://www.gnu.org/licenses/agpl-3.0.en.html
externalDocs:
  description: GitHub Repository
  url: https://github.com/osu-mist/web-api-skeleton
host: localhost
schemes:
  - http
basePath: /api/v0
consumes:
  - text/plain
produces:
  - application/json
paths:
  /:
    get:
      summary: Get information
      description: Build and runtime information about the application.
      responses:
        200:
          description: Object containing information
          schema:
            $ref: '#/definitions/Info'
  /sample:
    get:
      summary: Get message
      description: This is a sample resource that returns a short message.
      responses:
        200:
          description: A short message
          schema:
            type: string
        404:
          description: Not found
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Post message
      description: This is a sample resource that returns the message it receives.
      parameters:
        - name: message
          in: body
          schema:
            type: string
          required: true
      responses:
        200:
          description: The message received
          schema:
            type: string
        404:
          description: Not found
          schema:
            $ref: '#/definitions/Error'
definitions:
  Info:
    properties:
      name:
        type: string
      time:
        type: integer
      commit:
        type: string
      documentation:
        type: string
  Error:
    properties:
      status:
        type: integer
      developerMessage:
        type: string
      userMesage:
        type: string
      code:
        type: integer
      details:
        type: string
