swagger: '2.0'
info:
  title: University Recommendation API
  description: "This portion of the API aims at providing a list of recommendation of universities based on a student's ranking or score."
  version: '1.0'
schemes:
  - http
basePath: /api/v1
consumes:
  - text/plain
produces:
  - application/json
paths:
  /recommendations:
    get:
      tags:
        - recommendations
      description: "Get a list of statistical data of the universities based on a student's ranking or score difference between a student's score and the batch score; if majors are given, returns the statistics related to the majors."
      operationId: getRecommendations
      produces:
        - application/json
      parameters:
        - name: by
          in: query
          description: "Get recommendation by: ranking/score-diff"
          type: string
          required: true
        - name: student_type
          in: query
          description: "Type of student: arts/sciences"
          required: true
          type: string
        - name: province
          in: query
          description: "Province that the student took the College Entrance Examination"
          required: true
          type: string
        - name: batch
          in: query
          description: "Batch that the student belongs to"
          required: true
          type: integer
          format: int32
        - in: query
          name: lower_limit
          description: "Minimum ranking/score-diff of the student"
          required: true
          type: integer
          format: int32
        - in: query
          name: upper_limit
          description: "Maximum ranking/score-diff of the student"
          required: true
          type: integer
          format: int32
        - in: query
          name: year
          required: false
          description: "Year of the records"
          type: integer
          format: int32
        - in: query
          name: major
          description: "key word of the major name in Chinese"
          required: false
          type: string
        - in: query
          name: language
          description: "Display Language: EN/CN; Major translation is not supported in this version"
          type: string
          required: false
        - in: query
          name: page_size
          description: "Number of results to return. Used in pagination. Default value is 10."
          required: false
          type: integer
          format: int32
        - in: query
          name: page_number
          description: "Page number of results. Used to paginate through results. Default value is 1."
          required: false
          type: integer
          format: int32
      responses:
        "200":
          description: "Successful response"
          schema:
            $ref: "#/definitions/Recommendations"
        "204":
          description: "No content"
          schema:
            $ref: "#/definitions/Error"
        "404":
          description: "Not found"
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/Error"

definitions:
# ----------------------------------------------------------
# Recommendation object
# ----------------------------------------------------------
  Recommendation:
    type: object
    properties:
      university:
        $ref: "#/definitions/University"
      major:
        type: string
      year:
        type: integer
        format: int32
      stuCount:
        type: integer
        format: int32
        description: "Number of students enrolled in the university in the given year"
      scoreAvg:
        type: integer
        format: int32
        description: "Average score for the university"
      rank:
        type: integer
        format: int32
        description: "Ranking of the score in the province"
      scoreBatch:
        type: integer
        format: int32
        description: "Minimum score of the batch that the students is in"
      scoreDiff:
        type: integer
        format: int32
        description: "Differences between score_avg and score_batch"

  Recommendations:
    title: ArrayOfRecommendation
    type: array
    items:
      $ref: "#/definitions/Recommendation"

# ----------------------------------------------------------
# University object
# ----------------------------------------------------------
  University:
    type: object
    properties:
      name:
        type: string
        description: "Name of the university"
      is985:
        type: boolean
        description: "Is the university in the 985 program"
      is211:
        type: boolean
        description: "Is the university in the 211 program"

# ----------------------------------------------------------
# Error object
# ----------------------------------------------------------
  Error:
    type: object
    properties:
      status:
        type: integer
        format: int32
      developerMessage:
        type: string
      userMesage:
        type: string
      code:
        type: integer
      details:
        type: string
